docs/README.md

setup docs for GitHub Pages

---

charts/wildfly/README.md
charts/wildfly/values.schema.json

[#12] add build.pullSecret to wildly schema

---

examples/todo-backend/README.adoc
examples/todo-backend/todo-backend-bootable-jar.yaml
examples/todo-backend/todo-backend-s2i.yaml

[#14] Provide Helm Charts for the todo-backend quickstart

---

charts/wildfly/templates/NOTES.txt

the NOTE guides the user for the next steps to check the build and
deployment of the application.
This fixes #20.

[#20] add NOTES.txt

---

examples/todo-backend/todo-backend-s2i.yaml

Use the ejb-lite layer for the todo-backend S2I example

---

charts/wildfly/values.schema.json

Fix invalid schema

---

examples/microprofile-config/microprofile-config-app-s2i.yaml
examples/microprofile-config/microprofile-config-app.yaml
examples/todo-backend/todo-backend-bootable-jar.yaml
examples/todo-backend/todo-backend-s2i.yaml

Update Examples to use quickstarts 23.0.2.SP1 tag

---

README.md
charts/wildfly/README.md

Add badge to the project homepage
Update the chart readme to provide more context on its use (and the
requirement of providing an application image).

[#26] Register wildfly chart on artifacthub.io

---

.github/workflows/validation.yaml

add action to validate JSON schema and YAML examples

---

README.md

Adds Wiki link to the main readme file

Add wiki link to the main README file

---

charts/wildfly/README.md

Fix typos in README

---

index.md

add instructions to update the repository

---

index.md

Add sections about WildFly S2I compatibility

---

index.yaml

Add wildlfy-1.5.5 release

---

charts/wildfly/Chart.yaml

Bump wildfly Chart.version to 2.0.2

---

README.md

with the latest 2.x version, the output from command `helm search repo wildfly` has slightly changed

Fix README.md for 2.x

---

charts/wildfly-common/Chart.yaml
charts/wildfly-common/templates/_deployment.yaml
charts/wildfly/Chart.yaml

[#81] Remove AUTO_DEPLOY_EXPLODED=false from the deployment template

---

charts/wildfly-common/templates/_deployment.yaml
charts/wildfly/Chart.yaml
charts/wildfly/README.md
charts/wildfly/values.schema.json

[#82] Add deploy.imagePullSecrets field to pull from private registries

---

charts/wildfly/README.md

Sort all the fields in the lexical order.
This fixes #85.

[#85] Reorder the documentation tables

---

charts/wildfly/Chart.yaml

Bump wildfly to 2.2.0

---

charts/wildfly-common/Chart.yaml
charts/wildfly/Chart.yaml

Bump wildfly to 2.3.0

---

.gitignore
charts/wildfly/README.md
charts/wildfly/values.schema.json
examples/microprofile-config/README.adoc

Minor stuff, but some are user facing (that's how I noticed).

Minor spelling, style and formatting fixes across the project.

---

examples/todo-backend/todo-backend-bootable-jar.yaml

Updating the todo-backend example to match the Wildfly 27 quickstart

Update todo-backend to WildFly 27

---

charts/wildfly/README.md

Another random set of typos (just to avoid merge conflicts later).

Fix typos.

---

charts/wildfly-common/templates/_helpers.tpl
charts/wildfly-common/templates/_ingress.yaml
charts/wildfly/README.md
charts/wildfly/templates/ingress.yaml
charts/wildfly/templates/route.yaml
charts/wildfly/values.schema.json
charts/wildfly/values.yaml

Maybe I should disable ingress if route is enabled

Adding support to create an ingress entry

---

guides/kubernetes.adoc

Documentation for https://github.com/wildfly/wildfly-charts/pull/114

Adding documentation on how to set up Ingress on Kubernetes

---

.github/workflows/ci_kind.yaml
charts/wildfly/values.yaml
tests/bats/ingress.bats

Update startup probe
