wildfly/wildfly-charts

charts/wildfly-common/Chart.yaml
charts/wildfly-common/templates/_buildconfig-bootable-jar.yaml
charts/wildfly-common/templates/_buildconfig-s2i-build-artifacts.yaml
charts/wildfly-common/templates/_buildconfig-s2i.yaml
charts/wildfly-common/templates/_deployment.yaml
charts/wildfly-common/templates/_helpers.tpl
charts/wildfly-common/templates/_imagestream-s2i-build-artifacts.yaml
charts/wildfly-common/templates/_imagestream.yaml
charts/wildfly/Chart.yaml
charts/wildfly/README.md
charts/wildfly/templates/deployment.yaml
charts/wildfly/templates/imagestream.yaml
charts/wildfly/values.schema.json
charts/wildfly/values.yaml
examples/microprofile-config/README.adoc
examples/microprofile-config/microprofile-config-app-s2i.yaml
examples/microprofile-config/microprofile-config-app.yaml

* Switch from `DeploymentConfig` to `Deployment`
* Add build.output.kind and build.output.pushSecret to be able to build
an application image and push it to a Docker registry
This fixes #5

[#5] Enable deployment on Kubernetes

---

charts/wildfly/Chart.yaml
charts/wildfly/values.schema.json

The correct default value in the schema is set to s2i.
* Bump the wildfly's version to 1.2.0
This fixes #10.

[#10] Fix default value for build.mode

---

examples/todo-backend/todo-backend-s2i.yaml

Use `cloud-server` layer that contains all required dependencies
to buil a JAX-RS + JPA + CDI application. There is no need to add the
`ejb` or `ejb-lite` layer

Update Galleon Layers for todo-backend S2I example

---

charts/wildfly-common/Chart.yaml
charts/wildfly-common/templates/_buildconfig-s2i-build-artifacts.yaml
charts/wildfly/Chart.yaml
charts/wildfly/README.md
charts/wildfly/values.schema.json

For consistency with build.s2i.galleonLayers, build.s2i.featurePacks can
be either a CSV string or an array of strings.
this fixes #16.

[#16] Support Galleon dir and additional feature-packs

---

artifacthub-repo.yml

Add the artifacthub-repo.yml to claim ownership fo the wildfly chart and
be flagged as a verified publisher. 
This fixes #26

[#26] Register wildfly chart on artifacthub.io

---

charts/wildfly/Chart.yaml
examples/microprofile-config/microprofile-config-app-s2i.yaml
examples/microprofile-config/microprofile-config-app.yaml
examples/todo-backend/todo-backend-bootable-jar.yaml
examples/todo-backend/todo-backend-s2i.yaml

* Bum the version to 1.4.0
* Bump the appVersion to `24.0`
* Update the examples to use the 24.0.0.SP1 tag from the quickstarts
This fixes #29

[#29] Upgrade to WildFly 24.0

---

charts/wildfly/Chart.yaml
examples/microprofile-config/microprofile-config-app-s2i.yaml
examples/microprofile-config/microprofile-config-app.yaml
examples/todo-backend/todo-backend-bootable-jar.yaml
examples/todo-backend/todo-backend-s2i.yaml

- Bump the version to `1.4.1`
- Bump the appVersion to `24.0.1`
- Update the examples to use `24.0.1.Final` tag from the quickstarts
Fixes #38

[#38] Upgrade to WildFly 24.0.1

---

charts/wildfly/Chart.yaml

This chart requires at least Kubernetes 1.19.0 (which maps to OpenShift 4.6

add kubeVersion field

---

.github/workflows/validation.yaml
charts/wildfly/Chart.yaml
examples/microprofile-config/microprofile-config-app-s2i.yaml
examples/microprofile-config/microprofile-config-app.yaml
examples/todo-backend/todo-backend-bootable-jar.yaml
examples/todo-backend/todo-backend-s2i.yaml

* bump wildfly appVersion to 26.0 and version to 1.5.3
* refactor examples now that quickstarts can be built without requiring
to build their parent module first.

WildFly 26 release

---

charts/wildfly-common/Chart.yaml
charts/wildfly-common/templates/_buildconfig-s2i.yaml
charts/wildfly/Chart.yaml
charts/wildfly/README.md
charts/wildfly/templates/_helpers.tpl
charts/wildfly/templates/buildconfig-s2i.yaml
charts/wildfly/values.schema.json
charts/wildfly/values.yaml
examples/microprofile-config/README.adoc
examples/todo-backend/README.adoc

This major version relies on the new S2I images
for WildFly and the use of the wildfly-maven-plugin to
provision a server.
This major version will *not* work with older WildFly S2I images (from
https://quay.io/wildfly/wildfly-centos7)
* Set Chart's version to 2.0.0.
* Remove Chart's appVersion (as the WildFly version is no longer computed by the
Helm Chart)
* Update S2I BuildConfig to update the S2I output to /opt/server
* Remove build.s2i.version version
* Update build.s2i.builderImage & build.s2i.runtimeImage to point to the
new S2I images (including the tag in the names)

Helm Charts 2.0.0 for WildFly

---

charts/wildfly/Chart.yaml

Bump the appVersion to 26.1 after the release of the 26.1 S2I images
Bump the version to 1.5.5

WildFly 26.1 release

---

charts/wildfly/Chart.yaml

* Update `kubeVersion` to allow installation on pre-released version of
Kubernetes (after 1.19)
* bump `version` to 2.0.1 to prepare next release
This fixes #61

[#61] Allow prereleased version of Kubernetes

---

charts/wildfly/README.md
charts/wildfly/values.schema.json
examples/microprofile-config/microprofile-config-app-s2i.yaml
examples/todo-backend/todo-backend-s2i.yaml

Add notes that these fields are deprecated and using
wildfly-maven-plugin is the recommended way to provision WildFly during
S2I.
The `build.s2i.featurePacks` field *must* now specify all feature packs
(including WildFly own) if `build.s2i.galleonLayers` is set.
This fixes #69.

[#69] Deprecate build.s2i.galleonLayers and build.s2i.featurePacks

---

charts/wildfly-common/templates/_route.yaml
charts/wildfly/README.md
charts/wildfly/values.schema.json

If specified, the `deploy.route.host` field is used to set the host
alias for the `Route` resource created by the chart.
This fixes #71

[#71] Add `deploy.route.host` field

---

charts/wildfly-common/Chart.yaml
charts/wildfly/Chart.yaml
charts/wildfly/values.yaml

* add a `deploy.tls: {}` to the default values so that this field always
exist.
* bump wildfly-common chart version to 2.0.2
* bump wildfly chart version to 2.0.3
This fixes #72.

[#72] Add secure service for TLS support

---

charts/wildfly-common/Chart.yaml
charts/wildfly-common/templates/_buildconfig-bootable-jar.yaml
charts/wildfly-common/templates/_buildconfig-s2i-build-artifacts.yaml
charts/wildfly-common/templates/_deployment.yaml
charts/wildfly-common/templates/_helpers.tpl
charts/wildfly/Chart.yaml

Refactor the secret lookup so that it applies to all secrets expected by the Helm Chart
This fixes #89.

[#89] Verify that secrets exist before installing the Helm Release

---

charts/wildfly-common/templates/_helpers.tpl
charts/wildfly/README.md
charts/wildfly/templates/buildconfig-s2i.yaml
charts/wildfly/templates/imagestream.yaml
charts/wildfly/values.schema.json
charts/wildfly/values.yaml

If `build.s2i.buildApplication` is set to `false`, the resources to create the applicaition image are not generated.
In that case, the builder-artifacts image will take over the name of the Helm release (as it is the only produced image).
Deployment of the builder image can still happen and needs to be explicitely disabled with `deploy.enabled` set to `false` if needs be.
This fixes #93

[#93] Add the ability to skip building the application image

---

charts/wildfly-common/templates/_helpers.tpl

Set it to the name of the Release (instead of the name of the Helm Chart).
This fixes #109.

[#109] Update app.kubernetes.io/name label

---

charts/wildfly-common/Chart.yaml
charts/wildfly-common/templates/_deployment.yaml
charts/wildfly/Chart.yaml

* add the app.openshift.io/vcs-uri (resp. app.openshift.io/vcs-ref) if build is enabled and the `build.uri` (resp. `build.ref`) field is defined.
* bump wildfly-common version to 2.1.1
* bump wildfly version to 2.3.2
This fixes #106.

[#106] Add annotation to link the deployment to its source code

---

charts/wildfly-common/Chart.yaml
charts/wildfly/Chart.yaml

and wildfly-common to 2.2.0 after the introduction of the `deploy.ingress` capability in #114

Bump wildfly to 2.4.0

---

charts/wildfly/README.md
charts/wildfly/templates/buildconfig-bootable-jar.yaml
charts/wildfly/templates/buildconfig-s2i-build-artifacts.yaml
charts/wildfly/templates/buildconfig-s2i.yaml
charts/wildfly/templates/imagestream.yaml

* Checking if "build.openshift.io/v1" is supported to create the build part / imagestreams
Issue: https://github.com/wildfly/wildfly-charts/issues/129

Make the build step of the Helm Chart conditional on OpenShift resources

---

charts/wildfly-common/templates/_ingress.yaml

Checking if the .Values.deploy.ingress.tls is defined before checking for .Values.deploy.ingress.tls.secret
Issue: https://github.com/wildfly/wildfly-charts/issues/135

Fixing Nil Pointer Exception when using Ingress without TLS 

---

.github/workflows/ci/setup-image-registry.sh
.github/workflows/ci_kind.yaml
.github/workflows/helm.yaml
charts/wildfly/Chart.yaml
cr.yml
tests/bats/ingress.bats
tests/bats/metadata.bats
tests/bats/setup_suite.bash

Adding some annotationsto help with ArtifactHub
Signing our releases

Signing the releases
